### ISSUE TITLE
Include link for Chrome Extension on Rizzoma's How-to

### ISSUE THREAD

**Issue by lucianosb** [ZMYaro/wave-extensions-gallery#19]
We have that new possibilty of adding WEG's extensions to Rizzoma. It only lacks documentation on WEG.

**Comment by ZMYaro** [comment]
I do not follow; can you explain in more detail?

**Comment by lucianosb** [comment]
There is a page on the help section teaching how to install WEG's gadgets on each wave-based service we have today. I suggested to add on the Rizzoma page the WEG Search Chrome Extension.

**Comment by ZMYaro** [comment]
Oh, that is not a bad idea.

**Comment by ZMYaro** [comment]
Added in https://github.com/zmyaro/wave-extensions-gallery/commit/388407709a085499d4487a51c5f08804834b504f.
