### ISSUE TITLE
Your wave ui download link does not work 

### ISSUE THREAD

**Issue by topstarnetwork** [ZMYaro/wave-extensions-gallery#25]
Hello,
Your wave ui download link http://zmyaro.com/wave/ui.html does not work ,
would you have a github repository of it here?
Regards, Heather

**Comment by ZMYaro** [comment]
I apologize for the error, and for taking so long to correct it.  The link should be fixed now.

I might move the library to its own repo at some point, but I do not currently have any plans to do anything new with my wave.ui.css library.

**Comment by topstarnetwork** [comment]
Thanks a lot for yuor response,
regards, Heather
